/**
 * Refresh a saved report.
 *
 * Re-executes the report's stored SQL against the lab DB. Doesn't
 * re-ask the LLM — fast and deterministic. Still passes through
 * access-control and SQL safety checks because:
 *   1. The user's allowed-scope may have changed since save.
 *   2. The SQL was generated by an LLM and we trust validators more
 *      than the model's track record from yesterday.
 *
 * Returns the fresh LabQueryResult and updates the report's
 * lastRunAt / lastSummary / sql (if access-control rewrote it).
 */
import { enforceAccess } from "@/lib/validation/access-control";
import { validateSql, SqlValidationError } from "@/lib/validation/safety";
import { clampResultLimit } from "@/lib/validation/query-limit";
import { runLabQuery, type LabQueryResult } from "@/lib/db/lab";
import type { UserContext } from "@/lib/auth/rbac";
import {
  getReportForUser,
  summariseResult,
  updateReport,
} from "./store";

export interface RefreshOutcome {
  ok: boolean;
  reason?: string;
  result?: LabQueryResult;
}

export async function refreshReport(args: {
  reportId: string;
  userContext: UserContext;
}): Promise<RefreshOutcome> {
  const report = await getReportForUser({
    reportId: args.reportId,
    userId: args.userContext.userId,
  });
  if (!report) return { ok: false, reason: "report not found" };
  if (!report.sql) {
    return {
      ok: false,
      reason: "report has no saved SQL — regenerate from the question first",
    };
  }

  const decision = enforceAccess(report.sql, args.userContext);
  if (!decision.allowed) {
    return {
      ok: false,
      reason: `access denied: ${decision.reason}`,
    };
  }

  const sql = decision.rewrittenSql ?? report.sql;

  try {
    validateSql(sql);
  } catch (err) {
    return {
      ok: false,
      reason:
        err instanceof SqlValidationError
          ? `validation failed: ${err.message}`
          : `validation failed: ${(err as Error).message}`,
    };
  }

  let result: LabQueryResult;
  try {
    result = await runLabQuery(clampResultLimit(sql));
  } catch (err) {
    return {
      ok: false,
      reason: `execution failed: ${(err as Error).message}`,
    };
  }

  await updateReport(args.reportId, args.userContext.userId, {
    sql,
    lastSummary: summariseResult(result),
    lastRunAt: new Date(),
  });

  return { ok: true, result };
}
