/**
 * Audit log writer — one row per query.
 *
 * Called by the API route after the stream has fully iterated, so we
 * have the final state in hand and can record SQL (both generated and
 * RBAC-rewritten), error stage, duration, token counts, etc.
 */
import { db } from "@/lib/db/app";
import { auditLog } from "@/lib/db/schema";
import type { GraphStateType } from "@/lib/graph/state";
import { env } from "@/lib/config/env";

export interface AuditWriteInput {
  question: string;
  state: GraphStateType;
  /** Original SQL generated by the LLM, before any RBAC rewrite. */
  generatedSql: string | null;
  /** Wall-clock duration from request entry to stream end. */
  durationMs: number;
}

export async function writeAuditLog(input: AuditWriteInput): Promise<string> {
  const { state } = input;

  const validationResult = state.sqlMeta
    ? {
        confidence: state.sqlMeta.confidence,
        assumptions: state.sqlMeta.assumptions,
        citations: state.sqlMeta.citations,
        clarification: state.sqlMeta.clarificationNeeded,
        tokenUsage: state.sqlMeta.tokenUsage,
      }
    : null;

  const [row] = await db
    .insert(auditLog)
    .values({
      userId: state.userContext?.userId ?? null,
      sessionId: state.sessionId ?? null,
      question: input.question,
      generatedSql: input.generatedSql,
      rewrittenSql: state.accessDecision?.rewrittenSql ?? null,
      accessDecision: state.accessDecision ?? null,
      validationResult,
      resultCount: state.results?.count ?? null,
      durationMs: input.durationMs,
      errorStage: state.error?.stage ?? null,
      errorMessage: state.error?.internalMessage ?? state.error?.message ?? null,
      traceId: state.traceId,
      llmProvider: env.LLM_PROVIDER,
      llmModel: state.sqlMeta?.modelId ?? env.LLM_MODEL,
    })
    .returning({ id: auditLog.id });

  return row.id;
}
