#!/usr/bin/env tsx
/**
 * Build the RAG corpus.
 *
 * Reads:
 *   corpus/schema.json           — generated by scripts/export-schema.ts
 *   lib/config/business-rules.ts — domain rules (privacy, defaults, intent)
 *   lib/config/field-guide.ts    — terminology, thresholds, patterns
 *
 * Emits:
 *   corpus/snippets.jsonl  (one Snippet JSON per line)
 *
 * Each snippet has { id, type, text, meta, tags }. The `text` is what gets
 * embedded; the rest rides along as the Qdrant point payload for filtering
 * and citation. Snippet types follow the retired Python rag-api so the
 * downstream graph nodes can filter by type identically.
 *
 * Usage:
 *   npm run rag:build
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {
  BUSINESS_RULES,
  FORBIDDEN_COLUMNS,
} from "@/lib/config/business-rules";
import {
  CLINICAL_THRESHOLDS,
  COLUMN_SEMANTICS,
  GENERIC_PATTERNS,
  QUERY_PATTERNS,
  TERMINOLOGY_MAPPING,
  TEST_TYPE_LOGIC,
} from "@/lib/config/field-guide";
import type { Snippet, SnippetType } from "@/lib/rag/snippets";

interface SchemaColumn {
  name: string;
  type: string;
  nullable: boolean;
  key: string | null;
  default: string | null;
  comment: string;
}
interface SchemaTable {
  name: string;
  type: "base table" | "view";
  columns: SchemaColumn[];
}
interface SchemaRelationship {
  from_table: string;
  from_column: string;
  to_table: string;
  to_column: string;
}
interface SchemaDoc {
  version: string;
  database: string;
  tables: Record<string, SchemaTable>;
  relationships: SchemaRelationship[];
  reference_data: Record<string, unknown>;
}

const SCHEMA_PATH = path.resolve("corpus/schema.json");
const OUT_PATH = path.resolve("corpus/snippets.jsonl");

function shortHash(input: string): string {
  return crypto.createHash("sha1").update(input).digest("hex").slice(0, 10);
}

function makeId(type: SnippetType, key: string): string {
  return `${type}:${key}#${shortHash(`${type}:${key}`)}`;
}

function main() {
  if (!fs.existsSync(SCHEMA_PATH)) {
    throw new Error(
      `corpus/schema.json not found. Run \`npm run schema:export\` first ` +
        `(or drop a manually-prepared schema.json into corpus/).`,
    );
  }

  const schema: SchemaDoc = JSON.parse(fs.readFileSync(SCHEMA_PATH, "utf-8"));
  const snippets: Snippet[] = [];

  buildTableSnippets(schema, snippets);
  buildColumnSnippets(schema, snippets);
  buildRelationshipSnippets(schema, snippets);
  buildRuleSnippets(snippets);
  buildSynonymSnippets(snippets);
  buildPatternSnippets(snippets);
  buildThresholdSnippets(snippets);
  buildTestTypeSnippets(snippets);

  const byType: Record<string, number> = {};
  for (const s of snippets) byType[s.type] = (byType[s.type] ?? 0) + 1;

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  const stream = fs.createWriteStream(OUT_PATH);
  for (const s of snippets) stream.write(`${JSON.stringify(s)}\n`);
  stream.end();

  console.log(`Wrote ${snippets.length} snippets to ${OUT_PATH}`);
  for (const [type, count] of Object.entries(byType).sort()) {
    console.log(`  ${type.padEnd(14)} ${count}`);
  }
}

function buildTableSnippets(schema: SchemaDoc, out: Snippet[]) {
  for (const t of Object.values(schema.tables)) {
    const colSummary = t.columns
      .slice(0, 12)
      .map((c) => c.name)
      .join(", ");
    const extra = t.columns.length > 12 ? `, +${t.columns.length - 12} more` : "";
    out.push({
      id: makeId("table", t.name),
      type: "table",
      text: `Table ${t.name} (${t.columns.length} columns): ${colSummary}${extra}`,
      meta: { table: t.name, columnCount: t.columns.length },
      tags: ["table", t.name],
    });
  }
}

function buildColumnSnippets(schema: SchemaDoc, out: Snippet[]) {
  const forbidden = new Set<string>(FORBIDDEN_COLUMNS);

  for (const t of Object.values(schema.tables)) {
    const semanticsForTable = COLUMN_SEMANTICS[t.name] ?? {};

    for (const c of t.columns) {
      const semantic = semanticsForTable[c.name];
      const baseDesc = semantic ?? c.comment;
      const sensitive = forbidden.has(c.name);

      const lines: string[] = [`${t.name}.${c.name} (${c.type})`];
      if (baseDesc) lines.push(baseDesc);
      if (c.key === "PRI") lines.push("Primary key.");
      else if (c.key === "MUL") lines.push("Indexed (foreign key / lookup).");
      if (!c.nullable) lines.push("NOT NULL.");
      if (sensitive) {
        lines.push("PII — never select. Aggregation allowed only via COUNT(DISTINCT ...).");
      }

      out.push({
        id: makeId("column", `${t.name}.${c.name}`),
        type: "column",
        text: lines.join(" "),
        meta: {
          table: t.name,
          name: c.name,
          sqlType: c.type,
          nullable: c.nullable,
          key: c.key,
          sensitive,
        },
        tags: [
          "column",
          t.name,
          c.name,
          ...(sensitive ? ["sensitive"] : []),
        ],
      });
    }
  }
}

function buildRelationshipSnippets(schema: SchemaDoc, out: Snippet[]) {
  for (const r of schema.relationships) {
    out.push({
      id: makeId(
        "relationship",
        `${r.from_table}.${r.from_column}->${r.to_table}.${r.to_column}`,
      ),
      type: "relationship",
      text: `${r.from_table}.${r.from_column} → ${r.to_table}.${r.to_column} (foreign key)`,
      meta: {
        from_table: r.from_table,
        from_column: r.from_column,
        to_table: r.to_table,
        to_column: r.to_column,
      },
      tags: ["relationship", r.from_table, r.to_table],
    });
  }
}

function buildRuleSnippets(out: Snippet[]) {
  // Privacy
  for (const col of BUSINESS_RULES.privacy.forbiddenColumns) {
    out.push({
      id: makeId("rule", `privacy.forbidden_column.${col}`),
      type: "rule",
      text: `Forbidden column (PII): ${col} — never SELECT. ${BUSINESS_RULES.privacy.privacyMessage}`,
      meta: {
        section: "privacy",
        column: col,
        priority: 1.5,
      },
      tags: ["rule", "privacy", "forbidden", col],
    });
  }

  for (const col of BUSINESS_RULES.privacy.allowAggregatedDistinct) {
    out.push({
      id: makeId("rule", `privacy.allow_distinct.${col}`),
      type: "rule",
      text: `Privacy carve-out: ${col} may appear inside COUNT(DISTINCT …) only — for unique-patient aggregates without exposing individuals.`,
      meta: {
        section: "privacy",
        column: col,
        priority: 1.2,
      },
      tags: ["rule", "privacy", "aggregated", col],
    });
  }

  // Default assumptions
  for (const [i, rule] of BUSINESS_RULES.defaultAssumptions.entries()) {
    out.push({
      id: makeId("rule", `default_assumptions.${i}`),
      type: "rule",
      text: rule,
      meta: { section: "default_assumptions", priority: 1.0 },
      tags: ["rule", "default_assumptions"],
    });
  }

  // Scope
  for (const [i, rule] of BUSINESS_RULES.queryScopeLimits.entries()) {
    out.push({
      id: makeId("rule", `scope.${i}`),
      type: "rule",
      text: rule,
      meta: { section: "scope", priority: 1.0 },
      tags: ["rule", "scope"],
    });
  }

  // Intent
  for (const [intent, ir] of Object.entries(BUSINESS_RULES.intentRules)) {
    for (const [i, rule] of ir.rules.entries()) {
      out.push({
        id: makeId("rule", `intent.${intent}.${i}`),
        type: "rule",
        text: `Intent=${intent}: ${rule}`,
        meta: { section: `intent.${intent}`, intent, priority: 1.0 },
        tags: ["rule", "intent", intent],
      });
    }
  }

  // Contextual
  for (const [section, rules] of Object.entries(BUSINESS_RULES.contextual)) {
    for (const [i, rule] of rules.entries()) {
      out.push({
        id: makeId("rule", `contextual.${section}.${i}`),
        type: "rule",
        text: `${section.toUpperCase()}: ${rule}`,
        meta: { section: `contextual.${section}`, priority: 0.9 },
        tags: ["rule", "contextual", section],
      });
    }
  }

  // Response formatting
  for (const [i, rule] of BUSINESS_RULES.responseFormatting.columnAliases.entries()) {
    out.push({
      id: makeId("rule", `formatting.aliases.${i}`),
      type: "rule",
      text: `Output formatting: ${rule}`,
      meta: { section: "formatting.column_aliases", priority: 0.8 },
      tags: ["rule", "formatting"],
    });
  }
  for (const [i, rule] of BUSINESS_RULES.responseFormatting.dataPresentation.entries()) {
    out.push({
      id: makeId("rule", `formatting.presentation.${i}`),
      type: "rule",
      text: `Output formatting: ${rule}`,
      meta: { section: "formatting.data_presentation", priority: 0.8 },
      tags: ["rule", "formatting"],
    });
  }
}

function buildSynonymSnippets(out: Snippet[]) {
  for (const [phrase, target] of Object.entries(TERMINOLOGY_MAPPING)) {
    const variants = phrase.split("|");
    for (const v of variants) {
      out.push({
        id: makeId("syn", `${v}->${target}`),
        type: "syn",
        text: `"${v.trim()}" ↔ ${target}`,
        meta: { phrase: v.trim(), mapsTo: target, priority: 1.1 },
        tags: ["syn", v.trim().replace(/\s+/g, "-")],
      });
    }
  }
}

function buildPatternSnippets(out: Snippet[]) {
  // Named query patterns
  for (const [name, p] of Object.entries(QUERY_PATTERNS)) {
    out.push({
      id: makeId("exemplar", `pattern.${name}`),
      type: "exemplar",
      text: `${p.description}\nPattern: ${p.pattern}${p.example ? `\nExample: ${p.example}` : ""}`,
      meta: {
        name,
        pattern: p.pattern,
        ...(p.example ? { example: p.example } : {}),
        priority: 1.0,
      },
      tags: ["exemplar", "pattern", name],
    });
  }

  // Generic "by X" patterns (per applicable table)
  for (const gp of GENERIC_PATTERNS) {
    for (const table of gp.appliesToTables) {
      const phrases = gp.phrasePattern.split("|");
      const text =
        `When user asks "${phrases[0].trim()}" against ${table}: ` +
        `${gp.description}. Use ${gp.pattern.replace(/{table}/g, table)}` +
        (gp.joinRequired
          ? ` with ${gp.joinRequired.replace(/{table}/g, table)}`
          : "") +
        (gp.selectAddition
          ? ` and SELECT ${gp.selectAddition.replace(/{table}/g, table)}`
          : "");

      out.push({
        id: makeId(
          "exemplar",
          `generic.${gp.phrasePattern.split("|")[0].replace(/\s+/g, "-")}.${table}`,
        ),
        type: "exemplar",
        text,
        meta: {
          table,
          phrases,
          pattern: gp.pattern.replace(/{table}/g, table),
          ...(gp.joinRequired
            ? { joinRequired: gp.joinRequired.replace(/{table}/g, table) }
            : {}),
          ...(gp.selectAddition
            ? { selectAddition: gp.selectAddition.replace(/{table}/g, table) }
            : {}),
          priority: 1.0,
        },
        tags: ["exemplar", "generic", table],
      });
    }
  }
}

function buildThresholdSnippets(out: Snippet[]) {
  for (const [testType, info] of Object.entries(CLINICAL_THRESHOLDS)) {
    if (info.thresholds) {
      for (const [name, t] of Object.entries(info.thresholds)) {
        out.push({
          id: makeId("threshold", `${testType}.${name}`),
          type: "threshold",
          text: `${t.description}. Condition: ${t.condition}.${t.clinicalMeaning ? ` Meaning: ${t.clinicalMeaning}.` : ""}`,
          meta: {
            testType,
            name,
            condition: t.condition,
            clinicalMeaning: t.clinicalMeaning ?? null,
            priority: 1.1,
          },
          tags: ["threshold", testType, name],
        });
      }
    }
    if (info.categories) {
      for (const [name, condition] of Object.entries(info.categories)) {
        out.push({
          id: makeId("threshold", `${testType}.${name}`),
          type: "threshold",
          text: `${testType.toUpperCase()} ${name}: ${condition}`,
          meta: {
            testType,
            name,
            condition,
            priority: 1.0,
          },
          tags: ["threshold", testType, name],
        });
      }
    }
  }
}

function buildTestTypeSnippets(out: Snippet[]) {
  for (const [name, info] of Object.entries(TEST_TYPE_LOGIC)) {
    const lines = [
      `Test type: ${name} → table ${info.table}.`,
      info.defaultDescription ?? "",
      info.primaryResultColumn
        ? `Primary result column: ${info.primaryResultColumn}.`
        : "",
      info.dateTestedColumn
        ? `Default date column: ${info.dateTestedColumn}.`
        : "",
      info.displayLabName
        ? `Display lab as: ${info.displayLabName} (never raw lab_id).`
        : "",
    ].filter(Boolean);
    out.push({
      id: makeId("test_type", name),
      type: "test_type",
      text: lines.join(" "),
      meta: { name, ...info, priority: 1.1 },
      tags: ["test_type", name, info.table],
    });
  }
}

main();
